name: Build and Deploy
'on':
  workflow_dispatch:
    inputs:
      deployArgs:
        description: Components to deploy
        type: choice
        options:
          - --message all
          - --only hosting
          - --only functions
          - --only firestore
          - --only storage
        required: true
        default: --message all
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Fake Firebase Config
        run: echo '{}' | jq '.' > './src/firebase/config.env.json'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:unit
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Set Firebase Config
        run: echo '${{ secrets.FIREBASE_CONFIG }}' | jq '.' > './src/firebase/config.env.json'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist    
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_I_M_LOOKING_FOR_A_JOB }}'
          channelId: live
          projectId: i-m-looking-for-a-job
